export const CONVERSATION_LOCK_LEASE_MS = 15_000;
export const CONVERSATION_LOCK_POLL_MS = 100;
export const MAX_CONVERSATION_LOCK_WAIT_MS = 1_500;
export const TRIM_MESSAGES_BATCH_SIZE = 100;
export const LIST_CONVERSATION_MESSAGES_BATCH_SIZE = 100;
export const AUTO_RESUME_IDLE_MS = 12 * 60 * 60 * 1_000;
export const STALE_CONTEXT_RESET_MS = 30 * 60 * 1_000;
export const REFERENCED_HISTORY_SIDE_MESSAGES = 5;
